### ISSUE TITLE
  WARNING: settings.json not found! Don't worry i'll create one.

### ISSUE THREAD

**Issue by lillois59** [maleksal/isearch-osint#5]
Hi bro, 

I've tried to run your script but it seem its doesn't work well in my MPB using python3 dlib and your project
I got some error like "error = json.loads(e.error_response)" and these bellow : (how I can fix it ?) shukran

 python3 isearch_osint.py  /Users/Apple/instagram-scraper-master/instagram-scraper/v******h/know_faces v*******h

 WARNING: settings.json not found! Don't worry i'll create one.
Traceback (most recent call last):
  File "/Users/Apple/isearch-osint/isearch_osint.py", line 51, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/Apple/isearch-osint/isearch_osint.py", line 31, in main
    client = InstagramClient(config_dir=CONFIG_DIR)
  File "/Users/Apple/isearch-osint/isearch/client.py", line 87, in __init__
    self.__login__(u, p)
  File "/Users/Apple/isearch-osint/isearch/client.py", line 37, in catch
    error = json.loads(e.error_response)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
sofiane-MacBook-Pro:isearch-osint Apple$ 

fixed !!!! (venv) using virtural envi

**Comment by malek10xdev** [comment]
Hi @camillegroult 
Sorry for the delay, and thank you for reporting.
I'm working on a better version of this project and it'll be available soon.

**Comment by lillois59** [comment]
Hello @maleksal  salam bro, 

Ive today worked again on it using python3.6 but I dont know why its only download picture but not compare them cmd =  python3.6 isearch_osint.py /Users/Apple/output/someone  someonesle 

resutat only donwload picture and post 

best regard
